FROM node:18
RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY package*.json ./
RUN npm install --no-audit
COPY . .
RUN npx prisma generate
CMD ["npm", "test"]
